export {default as LoginForm} from './RegistroYSesion/LoginForm/LoginForm';
export {default as RutaProtegida} from './RegistroYSesion/RutaProtegida/RutaProtegida'
export {default as FormulariodeRegistro} from './RegistroYSesion/FormulariodeRegistro/FormulariodeRegistro';
export {default as NavBar} from './Navegacion/NavBar/NavBar'
export {default as Footer} from './Navegacion/Footer/Footer'
export {default as CarruselPeliculas} from './PaginaHome/CarruselPeliculas/CarruselPeliculas'
export {default as Destacadas} from './PaginaHome/Destacadas/Destacadas'
export {default as CategoriasPeliculas} from './PaginaHome/CategoriasPeliculas/CategoriasPeliculas'
export {default as BannerInicio} from './PaginaInicial/BannerInicio/BannerInicio'
export {default as Dispositivos} from './PaginaInicial/Dispositivos/Dispositivos'
export {default as Faqs} from './PaginaInicial/Faqs/Faqs'
export {default as Planes} from './PaginaInicial/Planes/Planes'
export {default as Servicios} from './PaginaInicial/Servicios/Servicios'
export {default as CardPelicula} from './SeccionPeliculas/CardPelicula/CardPelicula'
export {default as GridPelicula} from './SeccionPeliculas/GridPelicula/GridPelicula'
export {default as FormAgregar} from './Administracion/FormAgregar/FormAgregar';
export {default as ButtonsActions} from './Administracion/ButtonsActions/ButtonsActions';
export {default as HeaderAdmin} from './Administracion/HeaderAdmin/HeaderAdmin';
export {default as TableMovies} from './Administracion/TableMovies/TableMovies';
export{default as Error404} from './Error404/Error404'
export {default as GridPeliculaFavoritos} from './SeccionFavoritos/GridPeliculaFavoritos/GridPeliculaFavoritos'
