export {default as HomeRegistroYSesion} from './HomeRegistroYSesion/HomeRegistroYSesion';
export {default as LoginForm} from './LoginForm/LoginForm';
export {default as RutaProtegida} from './RutaProtegida/RutaProtegida'
export {default as FormulariodeRegistro} from './FormulariodeRegistro/FormulariodeRegistro';
export {default as NavBar} from './NavBar/NavBar'
export {default as Footer} from './Footer/Footer'
export {default as CarruselPeliculas} from './CarruselPeliculas/CarruselPeliculas'
export {default as Destacadas} from './Destacadas/Destacadas'
export {default as CategoriasPeliculas} from './CategoriasPeliculas/CategoriasPeliculas'
export {default as BannerInicio} from './BannerInicio/BannerInicio'
export {default as Dispositivos} from './Dispositivos/Dispositivos'
export {default as Faqs} from './Faqs/Faqs'
export {default as Planes} from './Planes/Planes'
export {default as Servicios} from './Servicios/Servicios'
export {default as CardPelicula} from './CardPelicula/CardPelicula'
export {default as GridPelicula} from './GridPelicula/GridPelicula'
export {default as FormAgregar} from './Administracion/FormAgregar/FormAgregar';
export {default as ButtonsActions} from './Administracion/ButtonsActions/ButtonsActions';
export {default as HeaderAdmin} from './Administracion/HeaderAdmin/HeaderAdmin';
export {default as TableMovies} from './Administracion/TableMovies/TableMovies';
export{default as Error404} from './Error404/Error404'
